# Generated by GitHub Copilot.

{
  description = ''
    A collection of niche Nix utilities that fulfil quite specific tasks.
    https://github.com/Ezjfc/nixche | Unlicense
  '';

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system: let
      pkgs = nixpkgs.legacyPackages.${system};
      nixche = self.packages.${system};
    in {
      packages = {
        create-netbeans-java-platform' = pkgs.callPackage ./java/create-netbeans-java-platform/package.nix {};
        write-cat-script' = pkgs.callPackage ./sh/write-cat-script/package.nix {};
        write-alias-script = pkgs.callPackage ./sh/write-alias-script/package.nix {};
        neovim-with-lsps = pkgs.callPackage ./neovim/neovim-with-lsps/package.nix {};
        neovim-auto-run = pkgs.callPackage ./neovim/neovim-auto-run/package.nix {};

        # Deprecated items, for backward compatibility:
        create-netbeans-java-platform = pkgs.writeText "create-netbeans-java-platform"
          (builtins.readFile ./java/create-netbeans-java-platform);
        write-cat-script = pkgs.writeText "write-cat-script"
          (builtins.readFile ./sh/write-cat-script);
      };

      # `neovim = null` will use the one that is installed externally:
      devShells.default = pkgs.callPackage ./shell.nix { inherit nixche; neovim = null; };
    }) // {
      overlays = {
        neovim-with-lsps = import ./neovim/neovim-with-lsps;
        neovim-auto-run = import ./neovim/neovim-auto-run;
      };
    };
}
