# Generated by GitHub Copilot

# Test file for write-cat-script
# Run with: nix-instantiate --eval --strict test.nix

let
  # Mock pkgs for testing
  mockPkgs = rec {
    writeShellScript = name: script: ''
      #!/usr/bin/env bash
      ${script}
    '';
    writeShellScriptBin = name: script: writeShellScript name script;
  };

  write-cat-utils = import ./default.nix {
    inherit (mockPkgs) writeShellScript writeShellScriptBin;
  };

  # Test writeCatScript with default colour
  test1 = write-cat-utils.writeCatScript "test-script" ''
    echo "Hello, World!"
  '';

  # Test writeCatScriptBin with default colour
  test2 = write-cat-utils.writeCatScriptBin "test-script-bin" ''
    echo "Hello from bin!"
  '';

  # Test writeCatScript with custom colour
  write-cat-utils-custom = import ./default.nix {
    inherit (mockPkgs) writeShellScript writeShellScriptBin;
    colour = "\\e[0;32m"; # Green
  };

  test3 = write-cat-utils-custom.writeCatScript "test-custom" ''
    echo "Custom colour test"
  '';

in {
  inherit test1 test2 test3;
  
  # Simple assertion tests
  assertions = {
    test1ContainsPurple = builtins.match ".*\\\\e\\[0;35m.*" test1 != null;
    test1ContainsReset = builtins.match ".*\\\\e\\[0m.*" test1 != null;
    test1ContainsCat = builtins.match ".*cat \\$0.*" test1 != null;
    test2ContainsEcho = builtins.match ".*echo \"Hello from bin!\".*" test2 != null;
    test3ContainsGreen = builtins.match ".*\\\\e\\[0;32m.*" test3 != null;
  };
}
