# Generated by GitHub Copilot

# Test file for neovim-enable-lsps
# Run with: nix-instantiate --eval --strict test.nix

let
  # Mock lib for testing
  mockLib = {
    concatStringsSep = sep: list:
      builtins.concatStringsSep sep list;
    assertMsg = cond: msg: cond || builtins.throw msg;
  };

  # Mock neovim package
  mockNeovim = {
    version = "0.11.0";
    pname = "neovim";
    meta = {};
    overrideAttrs = f: mockNeovim // (f {});
  };

  # Mock server packages
  mockServers = {
    lua_ls = "/nix/store/mock-lua-ls";
    nixd = "/nix/store/mock-nixd";
  };

  # Test: supportLsp is true for version 0.11.0
  test1 =
    (builtins.compareVersions "0.11.0" "0.11.0") > -1;

  # Test: supportLsp is true for version newer than 0.11.0
  test2 =
    (builtins.compareVersions "0.12.0" "0.11.0") > -1;

  # Test: supportLsp is false for version older than 0.11.0
  test3 =
    !((builtins.compareVersions "0.10.4" "0.11.0") > -1);

  # Test: serverNames and serverNamesDisplay
  serverNames = builtins.attrNames mockServers;
  serverNamesDisplay = mockLib.concatStringsSep " " serverNames;
  test4 = builtins.elem "lua_ls" serverNames && builtins.elem "nixd" serverNames;

  # Test: serverArgs construction
  serverArgs = builtins.concatMap (serverName: [
    "-c"
    "'lua vim.lsp.enable(\"${serverName}\")'"
  ]) serverNames;
  test5 = builtins.elem "'lua vim.lsp.enable(\"lua_ls\")'" serverArgs
       && builtins.elem "'lua vim.lsp.enable(\"nixd\")'" serverArgs;

in {
  inherit test1 test2 test3 test4 test5;

  # Simple assertion tests
  assertions = {
    newerVersionSupported = test1;
    evenNewerVersionSupported = test2;
    olderVersionNotSupported = test3;
    serverNamesCollected = test4;
    serverArgsConstructed = test5;
    serverNamesDisplayNotEmpty = serverNamesDisplay != "";
  };
}
